-- УДАЛЕНИЕ ПОДТВЕРЖДЕНО Русланом 02.09.2026 («дропай проверяй»).
--
-- Удаляются legacy-таблицы clients и owners. Проверено перед выполнением:
--   · код не обращается к ним ни разу (задача 17, коммит 7bcaf7e);
--   · owners пуста, в clients одна строка — она сохранена ниже дословно,
--     а недостающие поля перенесены в contacts предыдущей миграцией;
--   · колонки client_id/owner_id в contracts, deals, files, tasks — все пустые
--     (0 строк со значением), CASCADE снял только их FK-ограничения;
--   · представлений, триггеров и функций, зависящих от этих таблиц, не было —
--     только RLS-политики самих таблиц, они ушли вместе с ними.
--
-- Копия единственной строки clients на момент удаления:
-- {
--   "id": "6a3e74c4-9403-4a2f-92ef-1dc4559cbf1b",
--   "full_name": "Ножкин Руслан Сергеевич",
--   "phone": "+79607626799",
--   "telegram": "@nozhkin_r",
--   "passport": "0417167780",
--   "source": "referral",
--   "status": "new",
--   "comment": "Кайфовый клиент",
--   "whatsapp": null,
--   "birth_date": null,
--   "created_at": "2026-05-26T05:06:43.690354+00:00",
--   "manager_id": "508499ac-0268-49c7-9c31-8198deafeeda"
-- }
-- Двойник в contacts: d365ef50-2bee-4a6c-bc61-86f572e0cbc6
--
-- Колонки client_id/owner_id в contracts, deals, files, tasks остались как
-- обычные uuid без внешнего ключа. Отдельная задача — убрать и их.

DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS owners  CASCADE;
